# -*- coding: utf-8 -*-
"""datasetbueno.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BVaiQ9E8uCbdEu1LgLVELQ9RpV6nS152
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Cargar el dataset
df = pd.read_csv('dataset_limpio.csv')

# Configurar el estilo de los gráficos
sns.set_theme(style="whitegrid")
plt.rcParams['figure.figsize'] = (10, 6)

print("¡Dataset cargado con éxito!")
df.head() # Muestra las primeras filas

#📊 Comparación 1:
sns.countplot(data=df, y='Criterio de Seguridad Climática', palette='viridis')
plt.title('Distribución de Factores Críticos de Decisión')
plt.show()

"""Este gráfico nos dice qué sensor de nuestra estación es el más "esperado" por la comunidad.
**Comentario:** "Si la barra de 'Precipitaciones' es la más alta, nuestra estación debe ser infalible detectando lluvia, porque es lo que define si se hace o no una actividad".

"""

#📊 Comparación 2: Dolores a "Curar" por la Estación
sns.countplot(data=df, y='Criterio de Seguridad Climática', palette='viridis')
plt.title('Distribución de Factores Críticos de Decisión')
plt.show()

"""Aquí vemos la utilidad real (Product Discovery) de nuestro invento.

**Comentario**: "Si 'Salud y Bienestar' lidera, la estación no solo da el clima, sino que protege a los alumnos de alergias o golpes de calor".

"""

#📊 Comparación 3: Preocupación Ambiental según la Edad
sns.barplot(data=df, x='Edad', y='Prevencion_Ambiental', estimator=lambda x: (x == 'Sí').mean() * 100)
plt.ylabel('Porcentaje que eligió Cuidado Ambiental (%)')
plt.title('Conciencia Ambiental por Rango Etario')
plt.show()

"""¿A qué edad son más conscientes del impacto de la huella de carbono?
**Comentario: **"Este gráfico nos muestra si los más grandes o los más chicos están más alineados con el trabajo de los profes de Biología".

"""

#📊 Comparación 4: Interés en Evitar la "Parálisis por Información"
paralisis_counts = df['Prevencion_Info'].value_counts()
plt.pie(paralisis_counts, labels=paralisis_counts.index, autopct='%1.1f%%', colors=['#ff9999','#66b3ff'])
plt.title('¿Desean evitar el exceso de información técnica?')
plt.show()

"""¿Realmente necesitan una interfaz simple o les gustan los números complejos?

**Comentario: **"Si el 'Sí' es mayoritario, nuestra pantalla de la estación debe mostrar íconos claros y no solo una lista interminable de variables".

"""